name: Build IronPawn

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build Windows (${{ matrix.arch }})
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - arch: x64
            cmake_args: "-A x64"
            vcpkg_triplet: "x64-windows"
          - arch: x86
            cmake_args: "-A Win32"
            vcpkg_triplet: "x86-windows"

    steps:
    - uses: actions/checkout@v4

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install dependencies via vcpkg
      run: |
        vcpkg install curl nlohmann-json --triplet ${{ matrix.vcpkg_triplet }}

    - name: Configure CMake
      run: cmake -B build -S . ${{ matrix.cmake_args }} -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: IronPawn-Windows-${{ matrix.arch }}
        path: |
          build/Release/IronPawn.exe
